version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_NODEJS_CONNECTION_REUSE_ENABLED=1
      - AWS_SESSION_TOKEN
    ports:
      - 9000:8080
    expose:
      - 8080
    networks:
      internal_network:
  lre-proxy:
    image: lre-proxy:latest
    ports:
      - 9001:3000
    environment:
      - HOST_AND_PORT=app:8080
    networks:
      internal_network:

networks:
      internal_network: