# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# Workflow syntax reference:
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: PR Build

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # This is used by the SharedProps to detect a PR build
  PR_NUMBER: ${{ github.event.pull_request.number }}
  APP_NAME: nextjs-demo
  ENV: prod
  DEPLOYER_LAMBDA_NAME: microapps-core-ghpublic-deployer-prod
  AWS_REGION: us-east-2
  CDK_CONTEXT_ARGS: "--context @pwrdrvr/microapps:tableName=microapps-core-ghpublic-prod --context @pwrdrvr/microapps:s3BucketName=com.pwrdrvr.ghpublic.apps"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      prSuffix: ${{ steps.prSuffix.outputs.prSuffix }}
      packageVersion: ${{ steps.packageVersion.outputs.packageVersion }}
    steps:
      - uses: actions/checkout@v2

      - name: Compute PR Suffix
        id: prSuffix
        run: |
          if [ -n "${PR_NUMBER}" ]; then
            echo "::set-output name=prSuffix::-pr-${PR_NUMBER}"
            echo "PR_SUFFIX=-pr-"${PR_NUMBER} >> $GITHUB_ENV
          else
            echo "::set-output name=prSuffix::"
            echo "PR_SUFFIX=" >> $GITHUB_ENV
          fi

      - name: Extract Current NPM Version
        run: |
          echo 'PACKAGE_VERSION_ORIG='$(node -p -e "require('./package.json').version") >> $GITHUB_ENV

      - name: Compute NPM Version
        id: packageVersion
        run: |
          echo 'PACKAGE_VERSION='${PACKAGE_VERSION_ORIG}-pr.${PR_NUMBER} >> $GITHUB_ENV
          echo "::set-output name=packageVersion::${PACKAGE_VERSION_ORIG}-pr.${PR_NUMBER}"

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Node Modules
        run: npm ci

      - name: Link to node_modules - App
        working-directory: packages/app/node_modules
        run: ln -s ../../node_modules/.bin

      - name: Build All TypeScript
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Apply NPM Version
        run: |
          npm version ${PACKAGE_VERSION} --no-git-tag-version --workspaces

      - name: Create version.txt
        run: echo ${PACKAGE_VERSION} > version.txt
      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: version-txt
          path: version.txt

      - name: Apply Next.js Version
        run: |
          npx -w @pwrdrvr/microapps-app-nextjs-demo microapps-publish nextjs-version -n ${PACKAGE_VERSION}

      - name: Build Serverless Next.js
        run: |
          npx -w @pwrdrvr/microapps-app-nextjs-demo serverless

      - name: Copy in Serverless-NextJS-Router
        run: |
          npm run -w @pwrdrvr/microapps-app-nextjs-demo copy-router

      # We are using a shared Sharp node_modules layer
      - name: Remove Sharp from App Build
        working-directory: packages/app/
        run: |
          rm -rf .serverless_nextjs/image-lambda/node_modules

      # Upload Artifact
      - name: Zip Package
        working-directory: packages/app/
        run: zip -r serverless_nextjs.zip .serverless_nextjs
      - name: Upload Zip
        uses: actions/upload-artifact@v2
        with:
          name: app_zip
          path: packages/app/serverless_nextjs.zip

  deploy-ghpublic:
    needs:
      - build
    concurrency:
      group: deploy-ghpublic-${{ github.workflow }}-${{ github.event.pull_request.number }}
      cancel-in-progress: false
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: ghpublic
      url: https://apps.ghpublic.pwrdrvr.com/nextjs-demo/${{ needs.build.outputs.packageVersion }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Node Modules
        run: npm ci

      - name: Build All TypeScript
        run: npm run build

      - name: Download Artifact - App
        uses: actions/download-artifact@v2
        with:
          name: app_zip
          path: packages/app/
      - name: Unzip Artifact - App
        working-directory: packages/app/
        run: unzip serverless_nextjs.zip

      # Prevent the static files from getting pulled into the Lambda
      - name: Remove Static Files from App Build
        working-directory: packages/app/
        run: |
          mkdir .static_files
          mv .serverless_nextjs/assets .static_files

      - name: Download Artifact - Version.txt
        uses: actions/download-artifact@v2
        with:
          name: version-txt
      - run: echo PACKAGE_VERSION=$(cat version.txt) >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-session-name: microapps-app-nextjs-demo-build
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/builder-writeRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Preflight Check Version - App
        run: |
          npx microapps-publish preflight -a ${APP_NAME} -n ${PACKAGE_VERSION} -d ${DEPLOYER_LAMBDA_NAME} --overwrite

      - name: Deploy CDK Stack - App
        run: npx cdk deploy ${CDK_CONTEXT_ARGS} --hotswap --require-approval never app

      - name: Publish to MicroApps - App
        run: |
          npx microapps-publish publish -a ${APP_NAME} -n ${PACKAGE_VERSION} -d ${DEPLOYER_LAMBDA_NAME} -l microapps-app-${APP_NAME}-${ENV}-pr-${PR_NUMBER} -s packages/app/.static_files/assets/${APP_NAME}/${PACKAGE_VERSION} --overwrite --noCache

