name: Cleanup Merged PR

on:
  pull_request:
    types:
      - closed
    branches:
      - main

  workflow_dispatch:

# Limit concurrency to 1, with queueing, per workflow
# Limit concurrency to 1, with queueing, per workflow per PR
concurrency:
  group: build-${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: false
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  NODE_ENV: prod
  APP_NAME: nextjs-demo
  DEPLOYER_LAMBDA_NAME: microapps-core-ghpublic-deployer-prod
  AWS_REGION: us-east-2

jobs:
  cleanup-pr:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: ghpublic
    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install microapps-publish
        run: npm ci

      - name: Extract Current NPM Version
        run: |
          echo 'PACKAGE_VERSION_ORIG='$(node -p -e "require('./package.json').version") >> $GITHUB_ENV

      - name: Compute NPM Version
        id: packageVersion
        run: |
          echo 'PACKAGE_VERSION='${PACKAGE_VERSION_ORIG}-pr.${PR_NUMBER} >> $GITHUB_ENV
          echo "::set-output name=packageVersion::${PACKAGE_VERSION_ORIG}-pr.${PR_NUMBER}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-session-name: microapps-app-serverless-${{ env.APP_NAME }}-build
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/builder-writeRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Delete App from MicroApps
        run: |
          npx microapps-publish delete -a ${APP_NAME} -n ${PACKAGE_VERSION} -d ${DEPLOYER_LAMBDA_NAME}

      - name: Destroy CDK Stack
        run: |
          aws cloudformation delete-stack --stack-name "microapps-app-${APP_NAME}-${NODE_ENV}-pr-${PR_NUMBER}"
          aws cloudformation wait stack-delete-complete --no-paginate --output text --stack-name "microapps-app-${APP_NAME}-${NODE_ENV}-pr-${PR_NUMBER}"
